columns:
 - NPA Status
 - RevolvingUtilizationOfUnsecuredLines
 - age
 - Gender
 - Region
 - MonthlyIncome
 - Education
 - Rented_OwnHouse
 - Occupation
 - NumberOfTime30-59DaysPastDueNotWorse
 - DebtRatio
 - MonthlyIncome.1
 - NumberOfOpenCreditLinesAndLoans
 - NumberOfTimes90DaysLate
 - NumberRealEstateLoansOrLines
 - NumberOfTime60-89DaysPastDueNotWorse
 - NumberOfDependents
 - Good_Bad

numerical_columns:
 - NPA Status
 - RevolvingUtilizationOfUnsecuredLines
 - age
 - MonthlyIncome
 - NumberOfTime30-59DaysPastDueNotWorse
 - DebtRatio
 - MonthlyIncome.1
 - NumberOfOpenCreditLinesAndLoans
 - NumberOfTimes90DaysLate
 - NumberRealEstateLoansOrLines
 - NumberOfTime60-89DaysPastDueNotWorse

categorical_columns:
  -Gender
 - Region
 - Rented_OwnHouse
 - Occupation
 - Education
 - NumberOfDependents
 - Good_Bad

num_features:
 - NPA Status
 - RevolvingUtilizationOfUnsecuredLines
 - age
 - MonthlyIncome
 - NumberOfTime30-59DaysPastDueNotWorse
 - DebtRatio
 - MonthlyIncome.1
 - NumberOfOpenCreditLinesAndLoans
 - NumberOfTimes90DaysLate
 - NumberRealEstateLoansOrLines
 - NumberOfTime60-89DaysPastDueNotWorse

or_columns:
 - Rented_OwnHouse
oh_columns:

 - Gender
 - Region